"""add neutts reference data to voice profiles

Revision ID: 4effde802a12
Revises: 0a47ad8c8e82
Create Date: 2026-09-22 01:17:21.732274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4effde802a12'
down_revision: Union[str, Sequence[str], None] = '0a47ad8c8e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_profiles', sa.Column('reference_codes_path', sa.Text(), nullable=True))
    op.add_column('voice_profiles', sa.Column('reference_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voice_profiles', 'reference_text')
    op.drop_column('voice_profiles', 'reference_codes_path')
    # ### end Alembic commands ###
